---

- hosts: localhost
  become: yes
  become_user: root
  vars:
    public_key_file : "/root/.ssh/id_rsa.pub"
    meta_data_path : "/var/www/html/latest/meta-data"
    meta_data_template : "../../../../../conf/pxe_cluster/cloud-config.yaml.tmplt"

  tasks:
  - name: Check that the public ssh key exists
    stat:
      path: "{{ public_key_file }}"
    register: pub_key_exists

  - name: Creates ssh keys if one does not exist
    shell: "echo -e Y | ssh-keygen -b 2048 -t rsa -f {{ public_key_file }} -q -N \"\""
    when: pub_key_exists.stat.exists == False

  - name: Creates directory
    file:
      path: "{{ meta_data_path }}"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Apply template and copy meta-data file
    action: template src={{ meta_data_template }} dest={{ meta_data_path }}/{{ item }}
    vars:
      pub_key : "{{ lookup('file', '{{ public_key_file }}') }}"
    with_items:
      - "{{ target_macs }}"