# Copyright 2017 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
PROVISION:
  DHCP:
    subnet:
      -
        address: "10.30.5.0"
        bind_host:
          -
            ip: "10.30.5.12"
            mac: "3c:fd:fe:aa:b9:05"
          -
            ip: "10.30.5.13"
            mac: "3c:fd:fe:af:fa:c9"
          -
            ip: "10.30.5.14"
            mac: "3c:fd:fe:b0:24:91"
          -
            ip: "10.30.5.15"
            mac: "3c:fd:fe:af:fa:c5"
          -
            ip: "10.30.5.16"
            mac: "3c:fd:fe:af:fa:15"

        broadcast-address: "10.30.5.255"
        default-lease: 7600
        dn: cablelabs.com
        dns: "8.8.8.8"
        listen_iface: enp175s0f1
        max-lease: 7200
        name: Managment_SUBNET
        netmask: "255.255.255.0"
        range: "10.30.5.17 10.30.5.19"
        router: "10.30.5.1"
        type: management

  PROXY:
    ftp_proxy: ""
    http_proxy: "http://10.197.121.21:3142"
    https_proxy: ""
  PXE:
    password: cable123
    serverIp: "10.30.5.11"
    user: ubuntu
  STATIC:
    host:
     -
       access_ip: 10.30.5.12
       name: Controller
       interfaces:
         -
           address: "10.30.5.12"
           dn: ""
           dns: ""
           gateway: "0.0.0.0"
           iface: enp175s0f1
           name: Admin_Interface
           netmask: "255.255.255.0"
           type: management
         -
           address: "10.30.6.12"
           dn: ""
           dns: ""
           gateway: "0.0.0.0"
           iface: enp175s0f0
           name: Tenant_Interface
           netmask: "255.255.255.0"
           type: tenant
         -
           address: "10.30.7.12"
           dn: ""
           dns: ""
           gateway: "10.30.7.1"
           iface: enp24s0f1
           name: External_Interface
           netmask: "255.255.255.0"
           type: data
     -
        access_ip: 10.30.5.14
        name: Compute1
        interfaces:
          -
            address: "10.30.5.14"
            dn: ""
            dns: ""
            gateway: "0.0.0.0"
            iface: enp175s0f1
            name: Admin_Interface
            netmask: "255.255.255.0"
            type: management
          -
            address: "10.30.6.14"
            dn: ""
            dns: ""
            gateway: "0.0.0.0"
            iface: enp175s0f0
            name: Tenant_Interface
            netmask: "255.255.255.0"
            type: tenant
          -
            address: "10.30.7.14"
            dn: ""
            dns: ""
            gateway: "10.30.7.1"
            iface: enp24s0f1
            name: External_Interface
            netmask: "255.255.255.0"
            type: data
     -
        access_ip: 10.30.5.15
        name: Compute2
        interfaces:
          -
            address: "10.30.5.15"
            dn: ""
            dns: ""
            gateway: "0.0.0.0"
            iface: enp175s0f1
            name: Admin_Interface
            netmask: "255.255.255.0"
            type: management
          -
            address: "10.30.6.15"
            dn: ""
            dns: ""
            gateway: "0.0.0.0"
            iface: enp175s0f0
            name: Tenant_Interface
            netmask: "255.255.255.0"
            type: tenant
          -
            address: "10.30.7.15"
            dn: ""
            dns: ""
            gateway: "10.30.7.1"
            iface: enp24s0f1
            name: External_Interface
            netmask: "255.255.255.0"
            type: data

  BMC:
     host:
       -
         user: "admin"
         password: "cable123"
         ip: "10.30.8.12"
         mac: "a4:bf:01:3e:6d:9f"
       -
         user: "admin"
         password: "cable123"
         ip: "10.30.8.13"
         mac: "a4:bf:01:48:84:42"
       -
         user: "admin"
         password: "cable123"
         ip: "10.30.8.14"
         mac: "a4:bf:01:48:84:42"
       -
         user: "admin"
         password: "cable123"
         ip: "10.30.8.15"
         mac: "a4:bf:01:48:8b:11"
       -
         user: "admin"
         password: "cable123"
         ip: "10.30.8.16"
         mac: "a4:bf:01:48:84:34"
  TFTP:
    os: ubuntu-16.04.4-server-amd64.iso
    password: cable123
    seed: hwe-ubuntu-server.seed
    timezone: America/Denver
    user: ubuntu
    fullname: ubuntu_user
